"""create core webhook_subscriptions table

Revision ID: 01628d0d3eb6
Revises: 5d8c7a635e62
Create Date: 2026-09-07 15:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 4.3; docs/ARCHITECTURE.md section 4:
"core/webhooks -- Outbound webhook subscriptions, delivery, retry" --
`core.webhook_subscriptions`, owned exclusively by `core/webhooks`.

Isolation posture (`core/webhooks/models.py`'s own docstring, restated
here because it drives this migration's RLS decision):

`core.webhook_subscriptions` is tenant-owned and RLS-protected -- a
subscription always belongs to exactly one tenant, the simplest tenant-
owned shape already established for `core.roles` (`81ac56902107`): a
plain `tenant_id` foreign key to `core.tenants.id`, no composite FK (there
is no second identity, like a `user_id`, a subscription must additionally
belong to).

No `REVOKE` on this table (contrast with `2e7cb8c64903`'s `core.audit_log`,
which revokes UPDATE/DELETE for immutability): a subscription's row is
expected to be created and deleted in the ordinary course of
`subscribe()`/`unsubscribe()` -- the default grant (`e99c76057719`'s
`ALTER DEFAULT PRIVILEGES IN SCHEMA core` rule -- SELECT/INSERT/UPDATE/
DELETE) is exactly right here, unmodified.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "01628d0d3eb6"
down_revision: str | Sequence[str] | None = "5d8c7a635e62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "webhook_subscriptions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("signing_secret", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema="core",
    )
    op.create_index(
        "ix_webhook_subscriptions_tenant_id",
        "webhook_subscriptions",
        ["tenant_id"],
        schema="core",
    )

    for statement in tenant_rls_statements("webhook_subscriptions", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("webhook_subscriptions", schema="core")
