"""create core webhook_replay_records table

Revision ID: 2051d06ce0e7
Revises: 426db78eb60f
Create Date: 2026-09-09 06:00:00.000000

P1.10 -- Webhook Replay Protection. `core.webhook_replay_records`, owned
exclusively by `core/webhooks`.

Isolation posture (`core/webhooks/models.py::WebhookReplayRecord`'s own
docstring, restated here because it drives this migration's constraint
choices):

`core.webhook_replay_records` is tenant-owned and RLS-protected -- a
replay record always belongs to exactly one tenant, the same plain
`tenant_id`-FK shape `01628d0d3eb6`'s `core.webhook_subscriptions` and
`757d55add12a`'s `core.usage_events` already established. `subscription_id`
is a second FK (to `core.webhook_subscriptions.id`, not composite with
`tenant_id` -- a subscription id is already globally unique and already
tenant-scoped by its own row).

The `UniqueConstraint` on `(tenant_id, subscription_id, event_id)` is the
actual replay-detection mechanism (`core/webhooks/service.py::
record_webhook_delivery()`'s own docstring): a plain `INSERT` either
succeeds once or raises `IntegrityError` on any later duplicate attempt,
concurrent or sequential -- no `SELECT`-then-`INSERT` race window. The
unique index itself also serves as this table's primary lookup index for
`(tenant_id, subscription_id)`-scoped queries (`purge_expired_replay_records()`),
so no separate index on that prefix is added.

No `REVOKE` on this table (mirrors `757d55add12a`'s `core.usage_events`):
`purge_expired_replay_records()` needs ordinary `DELETE` privilege on the
restricted application role for its own retention cleanup, so none is
revoked -- the default grant (`e99c76057719`'s `ALTER DEFAULT PRIVILEGES
IN SCHEMA core` rule) is unmodified.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "2051d06ce0e7"
down_revision: str | Sequence[str] | None = "426db78eb60f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "webhook_replay_records",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column(
            "subscription_id",
            sa.Uuid(),
            sa.ForeignKey("core.webhook_subscriptions.id"),
            nullable=False,
        ),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "subscription_id",
            "event_id",
            name="uq_webhook_replay_records_tenant_subscription_event",
        ),
        schema="core",
    )
    op.create_index(
        "ix_webhook_replay_records_tenant_id",
        "webhook_replay_records",
        ["tenant_id"],
        schema="core",
    )

    for statement in tenant_rls_statements("webhook_replay_records", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("webhook_replay_records", schema="core")
