"""create core notifications table

Revision ID: 230aeac01e1b
Revises: 01628d0d3eb6
Create Date: 2026-09-07 17:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 4.4; docs/ARCHITECTURE.md section 4:
"core/notifications -- Notification dispatch pipeline" --
`core.notifications`, owned exclusively by `core/notifications`.

Isolation posture (`core/notifications/models.py`'s own docstring,
restated here because it drives this migration's constraint choices):

`core.notifications` is tenant-owned and RLS-protected -- a notification
always belongs to exactly one tenant and one recipient. Unlike
`core.webhook_subscriptions` (a plain `tenant_id` FK, no second identity
to guard), a notification's `(tenant_id, recipient_user_id)` pair must be
a genuine tenant membership -- the same composite-FK integrity guarantee
`81ac56902107` established for `core/rbac` in Phase 3.3 and `3a2522ccb9ea`
reused for `core/api_keys` in Phase 4.1, applied here identically: a row
can never reference a recipient who does not belong to that tenant,
enforced by Postgres itself via `(tenant_id, recipient_user_id) ->
tenant_memberships(tenant_id, user_id)`.

No `REVOKE` on this table (contrast with `2e7cb8c64903`'s `core.audit_log`):
a notification's row is written once by the dispatch job handler and
never updated/deleted by ordinary operation -- the default grant
(`e99c76057719`'s `ALTER DEFAULT PRIVILEGES IN SCHEMA core` rule --
SELECT/INSERT/UPDATE/DELETE) is unmodified; no acceptance criterion or
security requirement in this phase calls for immutability.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "230aeac01e1b"
down_revision: str | Sequence[str] | None = "01628d0d3eb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "recipient_user_id"],
            ["core.tenant_memberships.tenant_id", "core.tenant_memberships.user_id"],
            name="fk_notifications_tenant_membership",
        ),
        schema="core",
    )
    op.create_index("ix_notifications_tenant_id", "notifications", ["tenant_id"], schema="core")

    for statement in tenant_rls_statements("notifications", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("notifications", schema="core")
