"""create control_plane approval_requests table

Revision ID: 23310e44a21d
Revises: 757d55add12a
Create Date: 2026-09-08 12:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 7.2; docs/AI-CONTROL-PLANE.md
section 5 -- `control_plane.approval_requests`, owned exclusively by
`control_plane/approvals`.

This is the first table in the `control_plane` schema -- mirrors
`e99c76057719`'s own genesis-migration shape for `core` (`CREATE SCHEMA
IF NOT EXISTS`, `GRANT USAGE`, `ALTER DEFAULT PRIVILEGES`), applied here
to a second, independent schema. `control_plane.*` is AI Control Plane
data, never `core.*` (docs/ARCHITECTURE.md section 5: "each layer/module
owns a distinct schema").

Isolation posture (`control_plane/approvals/models.py`'s own docstring,
restated here because it drives this migration's RLS decision):
`control_plane.approval_requests` is tenant-owned and RLS-protected --
every proposed action, even one whose underlying tool is environment- or
repository-scoped rather than tenant-scoped, is still attributed to a
real `tenant_id` (required by `core.audit_log.record()`; see that
module's own "no tenant-less audit event" docstring). Gets the same RLS
treatment `infra.db.rls.tenant_rls_statements()` applies to any other
tenant-owned table.

No composite foreign key: `tenant_id` is a plain FK to `core.tenants.id`,
the same shape `core.billing_subscriptions`/`core.usage_events` already
use -- an approval request has no second identity (like a specific
tenant membership) it must additionally belong to.

No `REVOKE` on this table: rows are created and updated in the ordinary
course of `control_plane/approvals/service.py`'s own functions -- no
acceptance criterion or security requirement in this phase calls for
immutability (contrast `2e7cb8c64903`'s `core.audit_log`, which every
privileged action here is *additionally* recorded through, never
replaced by this table).

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

import os
import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "23310e44a21d"
down_revision: str | Sequence[str] | None = "757d55add12a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DEFAULT_APP_ROLE = "saas_os_app"


def _app_role() -> str:
    # Mirrors e99c76057719's own _app_role() helper exactly -- a role
    # NAME is not a secret (docs/ADR/0012-secrets-management.md is about
    # credential *values*).
    role = os.environ.get("APP_DB_USER", _DEFAULT_APP_ROLE)
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", role):
        raise ValueError(f"APP_DB_USER must be a plain SQL identifier, got: {role!r}")
    return role


def upgrade() -> None:
    app_role = _app_role()

    op.execute("CREATE SCHEMA IF NOT EXISTS control_plane")
    op.execute(f'GRANT USAGE ON SCHEMA control_plane TO "{app_role}"')

    op.create_table(
        "approval_requests",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("proposer_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=False),
        sa.Column("tool_key", sa.String(length=200), nullable=False),
        sa.Column("agent_scope_value", sa.String(length=255), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approver_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "approver_user_id IS NULL OR approver_user_id != proposer_user_id",
            name="ck_approval_requests_no_self_approval",
        ),
        schema="control_plane",
    )
    op.create_index(
        "ix_approval_requests_tenant_id", "approval_requests", ["tenant_id"], schema="control_plane"
    )

    op.execute(
        f'GRANT SELECT, INSERT, UPDATE, DELETE ON control_plane.approval_requests TO "{app_role}"'
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA control_plane "
        f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "{app_role}"'
    )

    for statement in tenant_rls_statements("approval_requests", schema="control_plane"):
        op.execute(statement)


def downgrade() -> None:
    app_role = _app_role()

    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA control_plane "
        f'REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM "{app_role}"'
    )
    op.drop_table("approval_requests", schema="control_plane")
    # No CASCADE: if a later migration has added another table to the
    # control_plane schema, this deliberately fails rather than silently
    # dropping data that does not belong to this migration.
    op.execute("DROP SCHEMA IF EXISTS control_plane")
