"""create core billing tables

Revision ID: 2d0730e14a7f
Revises: 230aeac01e1b
Create Date: 2026-09-07 19:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 5.1; docs/ADR/0008-billing-provider.md:
"Plans / Subscriptions / Entitlements / Invoices / Payments as distinct
concepts" -- `core.billing_plans` / `core.billing_subscriptions`, owned
exclusively by `core/billing`.

Isolation posture (`core/billing/models.py`'s own docstring, restated
here because it drives this migration's RLS decisions):

- `core.billing_plans` is a GLOBAL plan catalog, NOT RLS-scoped -- mirrors
  `core.feature_flags` (`5d8c7a635e62`): a plan definition is a
  platform/product pricing-tier declaration, not tenant-owned data.
- `core.billing_subscriptions` is a tenant-owned table and gets the same
  RLS treatment `infra.db.rls.tenant_rls_statements()` applies to any
  other tenant-owned table.

No composite foreign key here (contrast with `230aeac01e1b`'s
`core.notifications`): `plan_id` is a plain FK to the global
`billing_plans` table, the same shape as `core.webhook_subscriptions`'
plain `tenant_id` FK -- there is no second identity (like a user) a
subscription must additionally belong to, only the tenant itself.

No `REVOKE` on either table: plan/subscription rows are created and
updated in the ordinary course of `core/billing/service.py`'s own
functions -- the default grant (`e99c76057719`'s `ALTER DEFAULT
PRIVILEGES IN SCHEMA core` rule -- SELECT/INSERT/UPDATE/DELETE) is
unmodified; no acceptance criterion or security requirement in this
phase calls for immutability.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "2d0730e14a7f"
down_revision: str | Sequence[str] | None = "230aeac01e1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "billing_plans",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("key", sa.String(length=100), nullable=False, unique=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider_price_id", sa.String(length=255), nullable=True),
        sa.Column("entitlements", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema="core",
    )

    op.create_table(
        "billing_subscriptions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("plan_id", sa.Uuid(), sa.ForeignKey("core.billing_plans.id"), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("provider_subscription_id", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema="core",
    )
    op.create_index(
        "ix_billing_subscriptions_tenant_id", "billing_subscriptions", ["tenant_id"], schema="core"
    )

    for statement in tenant_rls_statements("billing_subscriptions", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    # Reverse dependency order: billing_subscriptions references billing_plans.
    op.drop_table("billing_subscriptions", schema="core")
    op.drop_table("billing_plans", schema="core")
