"""create core audit_log table

Revision ID: 2e7cb8c64903
Revises: 81ac56902107
Create Date: 2026-09-07 18:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 3.4; docs/SECURITY.md section 8;
docs/DATA-ARCHITECTURE.md section 7: `core.audit_log`, owned exclusively
by `core/audit_log`.

`core.audit_log` is tenant-owned and RLS-protected, exactly like
`core.roles`/`core.tenant_memberships`/`core.membership_roles` -- see
`core/audit_log/models.py`'s docstring for why no separate global/
tenant-less audit table is created in this phase.

**Immutability, enforced at the privilege level, not just by the absence
of an `update()`/`delete()` function in `core/audit_log/service.py`**: the
restricted runtime role (`APP_DB_USER`, default `saas_os_app`) is granted
SELECT/INSERT automatically by `e99c76057719`'s `ALTER DEFAULT PRIVILEGES
IN SCHEMA core` rule (which grants SELECT/INSERT/UPDATE/DELETE on every
table the bootstrap role subsequently creates) -- this migration explicitly
`REVOKE`s UPDATE and DELETE on this one table immediately after creating
it. This is the literal Security Requirement from
docs/IMPLEMENTATION-ROADMAP.md Phase 3.4: "verify no code path can mutate
or delete an existing entry, including via direct database access." A
direct `UPDATE core.audit_log ...` or `DELETE FROM core.audit_log ...`
issued as the application runtime role fails with a Postgres permission
error, independent of anything `core/audit_log/service.py` does or does
not expose.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

import os
import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "2e7cb8c64903"
down_revision: str | Sequence[str] | None = "81ac56902107"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DEFAULT_APP_ROLE = "saas_os_app"


def _app_role() -> str:
    # A role NAME is not a secret (docs/ADR/0012-secrets-management.md is
    # about credential *values*) -- read directly like other non-secret
    # deployment configuration, mirroring e99c76057719's own helper.
    # Restricted to a safe identifier shape since it is interpolated into
    # DDL text (op.execute has no identifier-binding mechanism) -- trusted
    # deployment configuration, not user input.
    role = os.environ.get("APP_DB_USER", _DEFAULT_APP_ROLE)
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", role):
        raise ValueError(f"APP_DB_USER must be a plain SQL identifier, got: {role!r}")
    return role


def upgrade() -> None:
    app_role = _app_role()

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column("action", sa.String(length=200), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "(actor_type = 'user' AND actor_user_id IS NOT NULL) "
            "OR (actor_type = 'system' AND actor_user_id IS NULL)",
            name="ck_audit_log_actor_type_user_id_pairing",
        ),
        sa.CheckConstraint("actor_type IN ('user', 'system')", name="ck_audit_log_actor_type"),
        sa.CheckConstraint(
            "outcome IN ('success', 'failure', 'denied')", name="ck_audit_log_outcome"
        ),
        sa.CheckConstraint(
            "metadata IS NULL OR octet_length(metadata::text) <= 8192",
            name="ck_audit_log_metadata_size",
        ),
        schema="core",
    )
    op.create_index(
        "ix_audit_log_tenant_created_at", "audit_log", ["tenant_id", "created_at"], schema="core"
    )
    op.create_index(
        "ix_audit_log_tenant_actor", "audit_log", ["tenant_id", "actor_user_id"], schema="core"
    )
    op.create_index(
        "ix_audit_log_tenant_resource",
        "audit_log",
        ["tenant_id", "resource_type", "resource_id"],
        schema="core",
    )

    for statement in tenant_rls_statements("audit_log", schema="core"):
        op.execute(statement)

    # Immutability at the privilege level -- see module docstring. The
    # runtime role already has SELECT/INSERT from e99c76057719's default-
    # privilege rule; this narrows it to exactly that, nothing more.
    op.execute(f'REVOKE UPDATE, DELETE ON core.audit_log FROM "{app_role}"')


def downgrade() -> None:
    op.drop_table("audit_log", schema="core")
