"""create core api_keys table

Revision ID: 3a2522ccb9ea
Revises: 2e7cb8c64903
Create Date: 2026-09-08 00:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 4.1; docs/ARCHITECTURE.md section 4:
"API key issuance, scoping, rotation, revocation" -- `core.api_keys`,
owned exclusively by `core/api_keys`.

Isolation posture (`core/api_keys/models.py`'s own docstring, restated
here because it drives this migration's constraint choices):

`core.api_keys` is GLOBAL -- NOT Row-Level-Security-scoped, mirroring
`core.sessions` (`770fe52b8468_create_core_identity_tables.py`): a bearer
credential must be resolvable by its hash *before* the caller's tenant is
known, and an untenanted query against an RLS-protected, FORCE-enabled
table always returns zero rows regardless of which row would have
matched. In RLS's place, a **composite foreign key**
`(tenant_id, user_id) -> core.tenant_memberships(tenant_id, user_id)` is
this table's substitute integrity guarantee: a key can only ever exist
for a user who is a genuine member of that tenant, enforced by Postgres
itself (the same composite-FK discipline `81ac56902107` established for
`core/rbac` in Phase 3.3, applied here to the one table that structurally
cannot use RLS instead).

No `REVOKE` on this table (contrast with `2e7cb8c64903`'s `core.audit_log`,
which revokes UPDATE/DELETE for immutability): unlike an audit record, a
key's row is *expected* to change -- `revoked_at` is set on revocation,
which is a normal, intended UPDATE. The default grant
(`e99c76057719`'s `ALTER DEFAULT PRIVILEGES IN SCHEMA core` rule --
SELECT/INSERT/UPDATE/DELETE) is exactly right here, unmodified.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a2522ccb9ea"
down_revision: str | Sequence[str] | None = "2e7cb8c64903"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False, unique=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"],
            ["core.tenant_memberships.tenant_id", "core.tenant_memberships.user_id"],
            name="fk_api_keys_tenant_membership",
        ),
        schema="core",
    )
    op.create_index("ix_api_keys_tenant_id", "api_keys", ["tenant_id"], schema="core")


def downgrade() -> None:
    op.drop_table("api_keys", schema="core")
