"""create core idempotency_records table

Revision ID: 3fb4e3e2f8de
Revises: 2051d06ce0e7
Create Date: 2026-09-09 07:00:00.000000

P1.11 -- Generic Idempotency. `core.idempotency_records`, owned
exclusively by `core/idempotency`.

Isolation posture (`core/idempotency/models.py::IdempotencyRecord`'s own
docstring, restated here because it drives this migration's constraint
choices):

`core.idempotency_records` is tenant-owned and RLS-protected -- a record
always belongs to exactly one tenant, the same plain `tenant_id`-FK shape
`757d55add12a`'s `core.usage_events` and `2051d06ce0e7`'s
`core.webhook_replay_records` already established.

The `UniqueConstraint` on `(tenant_id, operation, idempotency_key)` is
the actual race-protection mechanism
(`core/idempotency/service.py::run_idempotent()`/
`begin_idempotent_operation()`'s own docstrings): a plain `INSERT` either
succeeds once or raises `IntegrityError` on any concurrent/later
duplicate attempt -- no `SELECT`-then-`INSERT` race window. `operation`
is part of the key (not just `tenant_id` + `idempotency_key`) so two
different operations can never collide on a client-reused key string
(`core/idempotency/models.py`'s own docstring).

Unlike `2051d06ce0e7`'s `webhook_replay_records` (pure append-only
ledger), this table's rows legitimately transition `pending ->
succeeded` (or reset `pending`/`failed` -> `pending` for a retryable
abandoned attempt) -- hence `updated_at` (via the shared `TimestampMixin`,
`e99c76057719`'s own precedent) in addition to `created_at`.

No `REVOKE` on this table (mirrors `757d55add12a`/`2051d06ce0e7`):
`purge_expired_idempotency_records()` needs ordinary `DELETE` on the
restricted application role, and `status`/`result` need ordinary
`UPDATE` -- the default grant (`e99c76057719`'s own `ALTER DEFAULT
PRIVILEGES IN SCHEMA core` rule) is unmodified.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "3fb4e3e2f8de"
down_revision: str | Sequence[str] | None = "2051d06ce0e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "operation",
            "idempotency_key",
            name="uq_idempotency_records_tenant_operation_key",
        ),
        schema="core",
    )
    op.create_index(
        "ix_idempotency_records_tenant_id",
        "idempotency_records",
        ["tenant_id"],
        schema="core",
    )

    for statement in tenant_rls_statements("idempotency_records", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("idempotency_records", schema="core")
