"""create self_learning canaries table

Revision ID: 426db78eb60f
Revises: c0804e84948b
Create Date: 2026-09-08 10:59:41.617109

docs/IMPLEMENTATION-ROADMAP.md Phase 9.8 -- `self_learning.canaries`,
owned exclusively by
`control_plane/self_learning/autonomous_improvement`. Third table in the
`self_learning` schema, alongside `582f6b7865e7`'s
`self_learning.adaptations` (Phase 9.4) and `c0804e84948b`'s
`self_learning.experiments` (Phase 9.6), both of which this table
references directly via foreign key.

Isolation posture: tenant-owned and RLS-protected, same
`infra.db.rls.tenant_rls_statements()` treatment `self_learning.experiments`
and `self_learning.adaptations` already get -- Phase 9.8's own
Tenant-Isolation Requirement: "a canary/promotion decision for Tenant A's
scope never silently extends to Tenant B."

One `CHECK` constraint (`ck_canaries_status`) is the database-level half
of `control_plane/self_learning/autonomous_improvement/models.py`'s
`CanaryStatus` allowlist -- defense in depth against a direct-SQL bypass
of the Python enum, mirroring `c0804e84948b`'s own `ck_experiments_*`
constraints.

No `REVOKE` on this table: rows are mutable state, created and updated in
the ordinary course of
`control_plane/self_learning/autonomous_improvement/service.py`'s own
functions -- same discipline as `self_learning.experiments` (contrast
`2e7cb8c64903`'s `core.audit_log`, which every canary lifecycle
transition is *additionally* recorded through, never replaced by this
table).

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`) -- never the
restricted application runtime role, exactly like every migration since
Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately.
"""

import os
import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "426db78eb60f"
down_revision: str | Sequence[str] | None = "c0804e84948b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DEFAULT_APP_ROLE = "saas_os_app"


def _app_role() -> str:
    role = os.environ.get("APP_DB_USER", _DEFAULT_APP_ROLE)
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", role):
        raise ValueError(f"APP_DB_USER must be a plain SQL identifier, got: {role!r}")
    return role


def upgrade() -> None:
    app_role = _app_role()

    # self_learning schema already exists (582f6b7865e7), but this
    # migration must remain independently runnable/reversible without
    # assuming schema ownership sequencing beyond its declared down_revision.
    op.execute("CREATE SCHEMA IF NOT EXISTS self_learning")
    op.execute(f'GRANT USAGE ON SCHEMA self_learning TO "{app_role}"')

    op.create_table(
        "canaries",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "experiment_id",
            sa.Uuid(),
            sa.ForeignKey("self_learning.experiments.id"),
            nullable=False,
        ),
        sa.Column(
            "adaptation_id",
            sa.Uuid(),
            sa.ForeignKey("self_learning.adaptations.id"),
            nullable=False,
        ),
        sa.Column("candidate_version", sa.String(length=100), nullable=False),
        sa.Column("baseline_version", sa.String(length=100), nullable=False),
        sa.Column("policy_gate_decision_id", sa.Uuid(), nullable=False),
        sa.Column("monitoring_rules", sa.JSON(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=False),
        sa.Column("started_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column("concluded_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column("promoted_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column(
            "rolled_back_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True
        ),
        sa.Column("cancelled_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("concluded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rollback_reason", sa.String(length=500), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('configured', 'running', 'succeeded', 'promoted', "
            "'rolled_back', 'rollback_failed', 'cancelled')",
            name="ck_canaries_status",
        ),
        schema="self_learning",
    )
    op.create_index(
        "ix_canaries_tenant_status",
        "canaries",
        ["tenant_id", "status"],
        schema="self_learning",
    )
    op.create_index(
        "ix_canaries_tenant_experiment",
        "canaries",
        ["tenant_id", "experiment_id"],
        schema="self_learning",
    )

    op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON self_learning.canaries TO "{app_role}"')
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA self_learning "
        f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "{app_role}"'
    )

    for statement in tenant_rls_statements("canaries", schema="self_learning"):
        op.execute(statement)


def downgrade() -> None:
    app_role = _app_role()

    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA self_learning "
        f'REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM "{app_role}"'
    )
    op.drop_table("canaries", schema="self_learning")
    # No CASCADE, no DROP SCHEMA: self_learning.adaptations (582f6b7865e7)
    # and self_learning.experiments (c0804e84948b) still own this schema --
    # this downgrade must not drop a schema other tables still depend on.
