"""create core login_transactions table

Revision ID: 4c1e9a7b2d55
Revises: 3fb4e3e2f8de
Create Date: 2026-09-09 12:00:00.000000

P2.2 -- Production Authentication / OIDC HTTP flow.
`core.login_transactions`, owned exclusively by `core/identity`
(`core/identity/models.py::LoginTransaction`).

Isolation posture: global, NOT tenant-owned, NOT RLS-scoped -- exactly
like `770fe52b8468`'s `core.sessions`: a login transaction exists before
any user or tenant is known (it is the server-side half of an OIDC
Authorization Code login that has not completed yet). It references no
other table.

`state` is `UNIQUE`: two in-flight logins can never share a state value,
so a callback's `state` resolves to at most one transaction. Rows are
single-use and short-lived (`expires_at`), deleted by
`core.identity.login_transactions.consume_login_transaction()` in the
same transaction that validates them; `purge_expired_login_transactions()`
needs ordinary `DELETE` on the restricted application role, so the
default grant (`e99c76057719`'s `ALTER DEFAULT PRIVILEGES IN SCHEMA
core` rule) is unmodified -- no `REVOKE`.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c1e9a7b2d55"
down_revision: str | Sequence[str] | None = "3fb4e3e2f8de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "login_transactions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("state", sa.String(length=128), nullable=False, unique=True),
        sa.Column("nonce", sa.String(length=128), nullable=False),
        sa.Column("code_verifier", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema="core",
    )
    op.create_index(
        "ix_login_transactions_expires_at",
        "login_transactions",
        ["expires_at"],
        schema="core",
    )


def downgrade() -> None:
    op.drop_table("login_transactions", schema="core")
