"""create self_learning adaptations table

Revision ID: 582f6b7865e7
Revises: 23310e44a21d
Create Date: 2026-09-08 13:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 9.4; docs/AI-CONTROL-PLANE.md
section 12's L1 row -- `self_learning.adaptations`, owned exclusively by
`control_plane/self_learning/adaptive`.

This is the first table in the `self_learning` schema -- the namespace
Phase 9.1 (docs/IMPLEMENTATION-ROADMAP.md) reserved as a plain string
constant and never used until now. Mirrors `e99c76057719`'s and
`23310e44a21d`'s own genesis-migration shape (`CREATE SCHEMA IF NOT
EXISTS`, `GRANT USAGE`, `ALTER DEFAULT PRIVILEGES`), applied here to a
third, independent schema -- `self_learning.*` is AI Control Plane data,
never `core.*` (docs/ARCHITECTURE.md section 5).

Isolation posture: tenant-owned and RLS-protected, same
`infra.db.rls.tenant_rls_statements()` treatment every other tenant-owned
table gets (`core.audit_log`, `control_plane.approval_requests`).

Two `CHECK` constraints (`ck_adaptations_surface`, `ck_adaptations_status`,
`ck_adaptations_scope`, `ck_adaptations_evidence_type`,
`ck_adaptations_evaluation_outcome`) are the database-level half of the
typed-allowlist discipline `control_plane/self_learning/adaptive/models.py`
establishes in Python -- defense in depth against a direct-SQL bypass of
the Python enum (docs/IMPLEMENTATION-ROADMAP.md Phase 9.4's own
instruction: "do not rely solely on string prefix checks if an explicit
typed allowlist can prevent the problem structurally").

Two partial unique indexes enforce, at the database level, two invariants
`control_plane/self_learning/adaptive/service.py`'s own application logic
already maintains -- "the database is the real guarantee, the application
check is fail-fast" (the same discipline `core/rbac`'s composite foreign
keys and `control_plane/approvals`'s no-self-approval `CHECK` already
establish):

- `ux_adaptations_one_active_per_lineage`: at most one `ACTIVE` row per
  `(tenant_id, surface, lineage_key)` -- two concurrent activations for
  the same behavioral-configuration slot can never both succeed.
- `ux_adaptations_version_per_lineage`: version numbers are unique per
  lineage -- no two candidates for the same slot can ever collide on
  version.

No `REVOKE` on this table: rows are mutable state, created and updated in
the ordinary course of `control_plane/self_learning/adaptive/service.py`'s
own functions -- no acceptance criterion in this phase calls for
immutability (contrast `2e7cb8c64903`'s `core.audit_log`, which every
adaptation creation/activation/rollback is *additionally* recorded
through, never replaced by this table).

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`) -- never the
restricted application runtime role, exactly like every migration since
Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately.
"""

import os
import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "582f6b7865e7"
down_revision: str | Sequence[str] | None = "23310e44a21d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DEFAULT_APP_ROLE = "saas_os_app"


def _app_role() -> str:
    role = os.environ.get("APP_DB_USER", _DEFAULT_APP_ROLE)
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", role):
        raise ValueError(f"APP_DB_USER must be a plain SQL identifier, got: {role!r}")
    return role


def upgrade() -> None:
    app_role = _app_role()

    op.execute("CREATE SCHEMA IF NOT EXISTS self_learning")
    op.execute(f'GRANT USAGE ON SCHEMA self_learning TO "{app_role}"')

    op.create_table(
        "adaptations",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("surface", sa.String(length=40), nullable=False),
        sa.Column("lineage_key", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False, server_default="tenant"),
        sa.Column("proposed_value", sa.Text(), nullable=False),
        sa.Column(
            "previous_adaptation_id",
            sa.Uuid(),
            sa.ForeignKey("self_learning.adaptations.id"),
            nullable=True,
        ),
        sa.Column("learning_purpose", sa.String(length=200), nullable=False),
        sa.Column("evidence_type", sa.String(length=30), nullable=False),
        sa.Column("evidence_source_reference", sa.String(length=500), nullable=False),
        sa.Column("learning_authorization_decision_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_comparison_id", sa.Uuid(), nullable=True),
        sa.Column("evaluation_outcome", sa.String(length=20), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=False),
        sa.Column("activated_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column(
            "rolled_back_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "surface IN ('prompt_instruction', 'model_selection', 'routing_strategy', "
            "'tool_selection_strategy', 'retrieval_strategy', 'response_strategy', "
            "'personalization')",
            name="ck_adaptations_surface",
        ),
        sa.CheckConstraint(
            "status IN ('candidate', 'active', 'superseded', 'rolled_back')",
            name="ck_adaptations_status",
        ),
        sa.CheckConstraint("scope IN ('tenant', 'platform_wide')", name="ck_adaptations_scope"),
        sa.CheckConstraint(
            "evidence_type IN ('user_feedback', 'operator_feedback')",
            name="ck_adaptations_evidence_type",
        ),
        sa.CheckConstraint(
            "evaluation_outcome IS NULL OR evaluation_outcome IN "
            "('pass', 'fail', 'regression', 'invalid')",
            name="ck_adaptations_evaluation_outcome",
        ),
        schema="self_learning",
    )
    op.create_index(
        "ix_adaptations_tenant_lineage",
        "adaptations",
        ["tenant_id", "surface", "lineage_key"],
        schema="self_learning",
    )
    op.create_index(
        "ix_adaptations_tenant_status",
        "adaptations",
        ["tenant_id", "status"],
        schema="self_learning",
    )
    op.execute(
        "CREATE UNIQUE INDEX ux_adaptations_one_active_per_lineage "
        "ON self_learning.adaptations (tenant_id, surface, lineage_key) "
        "WHERE status = 'active'"
    )
    op.execute(
        "CREATE UNIQUE INDEX ux_adaptations_version_per_lineage "
        "ON self_learning.adaptations (tenant_id, surface, lineage_key, version)"
    )

    op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON self_learning.adaptations TO "{app_role}"')
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA self_learning "
        f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "{app_role}"'
    )

    for statement in tenant_rls_statements("adaptations", schema="self_learning"):
        op.execute(statement)


def downgrade() -> None:
    app_role = _app_role()

    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA self_learning "
        f'REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM "{app_role}"'
    )
    op.drop_table("adaptations", schema="self_learning")
    # No CASCADE: if a later migration has added another table to the
    # self_learning schema, this deliberately fails rather than silently
    # dropping data that does not belong to this migration.
    op.execute("DROP SCHEMA IF EXISTS self_learning")
