"""create core feature_flags tables

Revision ID: 5d8c7a635e62
Revises: 3a2522ccb9ea
Create Date: 2026-09-07 09:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 4.2; docs/ARCHITECTURE.md section 4:
"core/feature-flags -- Flag definitions, targeting rules, evaluation" --
`core.feature_flags` / `core.feature_flag_tenant_overrides`, owned
exclusively by `core/feature_flags`.

Isolation posture (`core/feature_flags/models.py`'s own docstring,
restated here because it drives this migration's RLS decisions):

- `core.feature_flags` is a GLOBAL flag catalog, NOT RLS-scoped -- mirrors
  `core.permissions` (`81ac56902107`): a flag definition is code/operator
  declared, not tenant-owned data.
- `core.feature_flag_tenant_overrides` is a tenant-owned table and gets
  the same RLS treatment `infra.db.rls.tenant_rls_statements()` applies to
  any other tenant-owned table.

No composite foreign key here (contrast with `81ac56902107`'s
`role_permissions`/`membership_roles`): `flag_id` is a plain FK to the
global `feature_flags` table, the same shape as `role_permissions.permission_id`
-- there is no tenant-owned parent to guard a composite FK against.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1. No explicit GRANT statements are needed for
either new table: `e99c76057719`'s `ALTER DEFAULT PRIVILEGES IN SCHEMA
core` rule already grants the runtime role
(`APP_DB_USER`, default `saas_os_app`) SELECT/INSERT/UPDATE/DELETE on
every table the same bootstrap role subsequently creates in `core`.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "5d8c7a635e62"
down_revision: str | Sequence[str] | None = "3a2522ccb9ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("key", sa.String(length=150), nullable=False, unique=True),
        sa.Column("enabled_by_default", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema="core",
    )

    op.create_table(
        "feature_flag_tenant_overrides",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("flag_id", sa.Uuid(), sa.ForeignKey("core.feature_flags.id"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint(
            "tenant_id", "flag_id", name="uq_feature_flag_tenant_overrides_tenant_flag"
        ),
        schema="core",
    )
    op.create_index(
        "ix_feature_flag_tenant_overrides_tenant_id",
        "feature_flag_tenant_overrides",
        ["tenant_id"],
        schema="core",
    )

    for statement in tenant_rls_statements("feature_flag_tenant_overrides", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    # Reverse dependency order: feature_flag_tenant_overrides references
    # feature_flags.
    op.drop_table("feature_flag_tenant_overrides", schema="core")
    op.drop_table("feature_flags", schema="core")
