"""add tenant hierarchy foundation (parent_id, core.tenant_ancestry)

Revision ID: 6b4f2d8a91c3
Revises: 4c1e9a7b2d55
Create Date: 2026-09-10 00:00:00.000000

Architecture research: universal multi-tenant tenancy, Phase A (ADR-0002
amendment -- "Tenant remains the canonical organization/isolation
abstraction" stays true; `Tenant` may now optionally participate in a
strict single-parent tree, structurally only, granting no authorization by
itself). See `core/tenancy/models.py` for the full invariants this
migration's schema enforces.

Two additive changes to the existing `core/tenancy` schema (Phase 3.1),
nothing removed or retyped:

1. `core.tenants` gains a nullable, self-referential `parent_id`. Every
   existing row gets `parent_id = NULL` (a plain `ADD COLUMN ... NULL`
   never infers or backfills a value) -- i.e. every tenant that existed
   before this migration remains a root tenant after it, with no other
   behavior change. A `CHECK` constraint blocks the one cycle a single
   `CHECK` can realistically catch without recursion: a tenant cannot be
   its own *direct* parent. Deeper cycles (a tenant moved beneath its own
   descendant) are not statically checkable by a `CHECK` constraint --
   that invariant is enforced at the application layer, transactionally,
   by `core/tenancy/service.py::move_tenant()`, which queries
   `core.tenant_ancestry` before writing anything (see that function's
   docstring); this is the realistic split between what PostgreSQL itself
   can enforce declaratively and what a security-critical, graph-shaped
   invariant needs a real query to check.

2. `core.tenant_ancestry` (new): the precomputed ancestor/descendant
   closure of `parent_id`, so "is X an ancestor of Y" is an indexed
   lookup, never a recursive CTE evaluated at read time (the exact
   Postgres RLS/query-planner performance trap the architecture research
   flags). One row per (tenant, ancestor) pair, including a *self* row
   (`tenant_id = ancestor_id`, `depth = 0`) for every tenant -- enforced
   by a `CHECK` constraint tying the self-row/`depth = 0` pairing
   together at the database level. Every pre-existing tenant is backfilled
   a self row below, since `core/tenancy/service.py::create_tenant()`
   populates one for every *new* tenant going forward and
   `core.tenant_ancestry` would otherwise be silently incomplete. Both of
   its foreign keys use `ON DELETE CASCADE` (unlike `parent_id`'s plain,
   non-cascading one above): a tenant's own ancestry rows have no meaning
   once the tenant is gone, so deleting any `Tenant` row -- via
   `purge_tenant()` or a raw `DELETE FROM core.tenants` -- always takes
   its ancestry rows with it in the same statement, in every code path,
   not just the one this migration's author happened to think of.

Neither table gets `infra.db.rls.tenant_rls_statements()` -- both are part
of the tenant *registry*'s own structure (like `core.tenants` itself,
`e99c76057719`), not tenant-*owned* business data; no RLS policy is added
or changed by this migration. No `SECURITY DEFINER`, no `BYPASSRLS`, no
change to `validate_application_role()` or the existing single-GUC
(`app.tenant_id`) isolation policy on any other table.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role. No explicit GRANT
statements are needed: `e99c76057719`'s `ALTER DEFAULT PRIVILEGES IN
SCHEMA core` rule already grants the runtime role
(`APP_DB_USER`, default `saas_os_app`) SELECT/INSERT/UPDATE/DELETE on any
new table the same bootstrap role creates in `core`, and `GRANT`s are
table-level (not column-level), so `core.tenants`' existing grant already
covers its new `parent_id` column with no further statement needed.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b4f2d8a91c3"
down_revision: str | Sequence[str] | None = "4c1e9a7b2d55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "tenants",
        sa.Column("parent_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=True),
        schema="core",
    )
    op.create_check_constraint(
        "ck_tenants_parent_not_self",
        "tenants",
        "parent_id IS NULL OR parent_id != id",
        schema="core",
    )

    op.create_table(
        "tenant_ancestry",
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            sa.ForeignKey("core.tenants.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "ancestor_id",
            sa.Uuid(),
            sa.ForeignKey("core.tenants.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.CheckConstraint("depth >= 0", name="ck_tenant_ancestry_depth_non_negative"),
        sa.CheckConstraint(
            "(tenant_id = ancestor_id AND depth = 0) OR (tenant_id != ancestor_id AND depth > 0)",
            name="ck_tenant_ancestry_self_row_iff_depth_zero",
        ),
        schema="core",
    )
    op.create_index(
        "ix_tenant_ancestry_ancestor_id", "tenant_ancestry", ["ancestor_id"], schema="core"
    )

    # Backfill: every tenant that already existed before this migration
    # becomes its own root self-ancestry row (depth 0) -- see module
    # docstring. `parent_id` is already NULL for all of them (root), so
    # no non-self ancestry rows are needed.
    op.execute(
        "INSERT INTO core.tenant_ancestry (tenant_id, ancestor_id, depth) "
        "SELECT id, id, 0 FROM core.tenants"
    )


def downgrade() -> None:
    op.drop_index("ix_tenant_ancestry_ancestor_id", table_name="tenant_ancestry", schema="core")
    op.drop_table("tenant_ancestry", schema="core")
    op.drop_constraint("ck_tenants_parent_not_self", "tenants", schema="core", type_="check")
    op.drop_column("tenants", "parent_id", schema="core")
