"""create core usage_events table

Revision ID: 757d55add12a
Revises: 2d0730e14a7f
Create Date: 2026-09-07 21:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 5.2; docs/DATA-ARCHITECTURE.md
section 6: "core/usage owns the canonical usage-event store and
aggregation logic" -- `core.usage_events`, owned exclusively by
`core/usage`.

Isolation posture (`core/usage/models.py`'s own docstring, restated here
because it drives this migration's constraint choices):

`core.usage_events` is tenant-owned and RLS-protected -- a usage event
always belongs to exactly one tenant. No composite foreign key here
(contrast with `230aeac01e1b`'s `core.notifications`): a usage event has
no second identity to guard against, only the tenant itself -- the same
plain-`tenant_id`-FK shape `2d0730e14a7f`'s `core.billing_subscriptions`
and `01628d0d3eb6`'s `core.webhook_subscriptions` already established.

No `REVOKE` on this table (contrast with `2e7cb8c64903`'s
`core.audit_log`): this phase's roadmap text does not mandate an
immutability enforcement requirement the way Phase 3.4 explicitly did for
the audit log -- the default grant (`e99c76057719`'s `ALTER DEFAULT
PRIVILEGES IN SCHEMA core` rule -- SELECT/INSERT/UPDATE/DELETE) is
unmodified. The table's own schema (no `updated_at` column) signals its
append-only intent without enforcing it at the privilege layer.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like every
migration since Phase 3.1.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "757d55add12a"
down_revision: str | Sequence[str] | None = "2d0730e14a7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "usage_events",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema="core",
    )
    op.create_index("ix_usage_events_tenant_id", "usage_events", ["tenant_id"], schema="core")

    for statement in tenant_rls_statements("usage_events", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("usage_events", schema="core")
