"""create core identity tables (users, external_identities, sessions, tenant_memberships)

Revision ID: 770fe52b8468
Revises: e99c76057719
Create Date: 2026-09-07 00:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 3.2; docs/DATA-ARCHITECTURE.md
section 1: `core.users` / `core.external_identities` / `core.sessions` /
`core.tenant_memberships`, owned exclusively by `core/identity`.

Isolation posture (`core/identity/models.py`'s own docstring, restated here
because it drives this migration's RLS decisions):

- `core.users`, `core.external_identities`, `core.sessions` are global --
  NOT Row-Level-Security-scoped, mirroring `core.tenants`
  (`e99c76057719_create_core_tenants_table.py`): resolving *which* user or
  session a request belongs to must be possible before any tenant context
  exists.
- `core.tenant_memberships` IS tenant-owned data and gets the same RLS
  treatment `infra.db.rls.tenant_rls_statements()` applies to any future
  tenant-owned table.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role, exactly like the tenants
migration. No explicit GRANT statements are needed here: `e99c76057719`'s
`ALTER DEFAULT PRIVILEGES IN SCHEMA core` rule already grants the runtime
role (`APP_DB_USER`, default `saas_os_app`) SELECT/INSERT/UPDATE/DELETE on
every table the *same bootstrap role* subsequently creates in `core` -- one
place to get this right, not something every future migration must repeat.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring
and `e99c76057719`'s): `infra/db` must not import `core`, so autogenerate
diffing against Core's tables is not wired.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "770fe52b8468"
down_revision: str | Sequence[str] | None = "e99c76057719"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema="core",
    )

    op.create_table(
        "external_identities",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=False),
        sa.Column("issuer", sa.String(length=2048), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("issuer", "subject", name="uq_external_identities_issuer_subject"),
        schema="core",
    )
    op.create_index(
        "ix_external_identities_user_id", "external_identities", ["user_id"], schema="core"
    )

    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False, unique=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        schema="core",
    )
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"], schema="core")

    op.create_table(
        "tenant_memberships",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_tenant_memberships_tenant_user"),
        schema="core",
    )
    op.create_index(
        "ix_tenant_memberships_user_id", "tenant_memberships", ["user_id"], schema="core"
    )

    for statement in tenant_rls_statements("tenant_memberships", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    # Reverse FK-dependency order: tenant_memberships/sessions/
    # external_identities all reference users, so users is dropped last.
    op.drop_table("tenant_memberships", schema="core")
    op.drop_table("sessions", schema="core")
    op.drop_table("external_identities", schema="core")
    op.drop_table("users", schema="core")
