"""create core rbac tables (roles, permissions, role_permissions, membership_roles)

Revision ID: 81ac56902107
Revises: 770fe52b8468
Create Date: 2026-09-07 12:00:00.000000

docs/IMPLEMENTATION-ROADMAP.md Phase 3.3; docs/DATA-ARCHITECTURE.md
section 1: `core.roles` / `core.permissions` / `core.role_permissions` /
`core.membership_roles`, owned exclusively by `core/rbac`.

Isolation posture (`core/rbac/models.py`'s own docstring, restated here
because it drives this migration's RLS decisions):

- `core.roles` is tenant-owned and RLS-protected -- a role is always local
  to one tenant.
- `core.permissions` is a GLOBAL capability catalog, NOT RLS-scoped --
  mirrors `core.tenants`/`core.users`: a permission definition
  (`resource` + `action`) is code-declared, not tenant-owned data.
- `core.role_permissions` and `core.membership_roles` are tenant-owned
  join tables and get the same RLS treatment
  `infra.db.rls.tenant_rls_statements()` applies to any other tenant-owned
  table.

Composite foreign keys (docs/IMPLEMENTATION-ROADMAP.md Phase 3.3 section
18): `role_permissions.(tenant_id, role_id)` and
`membership_roles.(tenant_id, role_id)` reference `roles(tenant_id, id)`;
`membership_roles.(tenant_id, membership_id)` references
`tenant_memberships(tenant_id, id)` -- so a row can never reference a role
or membership belonging to a different tenant, enforced by Postgres
itself. This requires `core.tenant_memberships` to expose a
`UNIQUE(tenant_id, id)` constraint it did not need in Phase 3.2 (added by
this migration, additive only -- no existing column, data, or behavior on
that table changes) and `core.roles` to expose the same shape (added at
creation time, below).

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role. No explicit GRANT
statements are needed for the four new tables: `e99c76057719`'s
`ALTER DEFAULT PRIVILEGES IN SCHEMA core` rule already grants the runtime
role (`APP_DB_USER`, default `saas_os_app`) SELECT/INSERT/UPDATE/DELETE on
every table the *same bootstrap role* subsequently creates in `core`.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "81ac56902107"
down_revision: str | Sequence[str] | None = "770fe52b8468"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Additive-only change to the Phase 3.2 table: required as the target
    # of membership_roles' composite FK below (see module docstring). No
    # existing column, row, or constraint on tenant_memberships changes.
    op.create_unique_constraint(
        "uq_tenant_memberships_tenant_id_id",
        "tenant_memberships",
        ["tenant_id", "id"],
        schema="core",
    )

    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("tenant_id", "name", name="uq_roles_tenant_name"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_roles_tenant_id_id"),
        schema="core",
    )

    op.create_table(
        "permissions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("resource", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("resource", "action", name="uq_permissions_resource_action"),
        schema="core",
    )

    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), sa.ForeignKey("core.permissions.id"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permissions_role_permission"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["core.roles.tenant_id", "core.roles.id"],
            name="fk_role_permissions_tenant_role",
        ),
        schema="core",
    )
    op.create_index("ix_role_permissions_role_id", "role_permissions", ["role_id"], schema="core")
    op.create_index(
        "ix_role_permissions_permission_id", "role_permissions", ["permission_id"], schema="core"
    )

    op.create_table(
        "membership_roles",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.UniqueConstraint("membership_id", "role_id", name="uq_membership_roles_membership_role"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["core.tenant_memberships.tenant_id", "core.tenant_memberships.id"],
            name="fk_membership_roles_tenant_membership",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["core.roles.tenant_id", "core.roles.id"],
            name="fk_membership_roles_tenant_role",
        ),
        schema="core",
    )
    op.create_index(
        "ix_membership_roles_membership_id", "membership_roles", ["membership_id"], schema="core"
    )
    op.create_index("ix_membership_roles_role_id", "membership_roles", ["role_id"], schema="core")

    for statement in tenant_rls_statements("roles", schema="core"):
        op.execute(statement)
    for statement in tenant_rls_statements("role_permissions", schema="core"):
        op.execute(statement)
    for statement in tenant_rls_statements("membership_roles", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    # Reverse dependency order: membership_roles/role_permissions
    # reference roles (and membership_roles additionally references
    # tenant_memberships); permissions has no dependents left once
    # role_permissions is gone.
    op.drop_table("membership_roles", schema="core")
    op.drop_table("role_permissions", schema="core")
    op.drop_table("permissions", schema="core")
    op.drop_table("roles", schema="core")
    op.drop_constraint(
        "uq_tenant_memberships_tenant_id_id", "tenant_memberships", schema="core", type_="unique"
    )
