"""add membership status and core.invitations

Revision ID: 87efe7908288
Revises: 9aecff1d1135
Create Date: 2026-09-11 00:00:00.000000

Architecture research: universal multi-tenant tenancy, Phase G
("Invitation / Membership Lifecycle"). See `core/identity/models.py
::MembershipStatus`/`TenantMembership`/`Invitation` for the full model
this migration's schema enforces, and `core/rbac/authorization.py::can()`
for how membership status gates ordinary and delegated authorization.

Two additive changes to the existing schema (Phases 3.1-3.4, A-F), nothing
removed or retyped:

`core.tenant_memberships` gains a `status` column, `NOT NULL` with
`server_default='active'` -- every row that already existed before this
migration becomes `'active'`: the exact, only behavior a `TenantMembership`
row could ever have meant before this phase existed. This is the "safe
default corresponding to the current authorization behavior" discipline
`a17e5f3c9d84` (membership-role scope) already established for this exact
kind of additive column. A `CHECK` constraint restricts the column to
`'active'`/`'suspended'`/`'revoked'` at the database level -- three
states, not four: an `INVITED` state was considered and dropped before
this migration was finalized (architecture research Phase G pre-checkpoint
review) because no code path in this phase ever produces it (`Invitation`'s
own docstring: acceptance always creates/activates a membership directly
as `ACTIVE`, never via an intermediate pending membership row).

`core.invitations` -- GLOBAL, like `core.sessions`/`core.api_keys`, NOT
Row-Level-Security-scoped: an invitation token must be resolvable by hash
before any tenant context exists (`Invitation`'s own docstring documents
the identical structural reasoning `ApiKey`/`Session` already establish).
`tenant_id` is a real, required column, just not RLS-enforced. Four
`CHECK` constraints enforce the pairing/mutual-exclusion invariants
`Invitation`'s own docstring describes (acceptance pairing, revocation
pairing, "not both accepted and revoked", valid time range). A partial
unique index (`uq_invitations_live_unique`) limits a `(tenant_id,
invited_email)` pair to at most one concurrently-pending invitation.

No RLS change to any other table, no `app.authorized_tenant_ids`, no
`SECURITY DEFINER`, no `BYPASSRLS`, no change to
`validate_application_role()`.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role. No explicit GRANT
statement is needed: `e99c76057719`'s `ALTER DEFAULT PRIVILEGES IN SCHEMA
core` rule already grants the runtime role (`APP_DB_USER`, default
`saas_os_app`) SELECT/INSERT/UPDATE/DELETE on any new table the same
bootstrap role creates in `core`; altering `core.tenant_memberships`'s
columns/constraints needs no new GRANT at all (grants are table-level, not
column-level).

Downgrade reverses every change in the opposite dependency order (drop
`core.invitations` first, since it has no dependents; then the
`tenant_memberships.status` column/constraint).

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87efe7908288"
down_revision: str | Sequence[str] | None = "9aecff1d1135"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- core.tenant_memberships: explicit lifecycle status --------------
    op.add_column(
        "tenant_memberships",
        sa.Column("status", sa.String(length=20), nullable=False, server_default="active"),
        schema="core",
    )
    op.create_check_constraint(
        "ck_tenant_memberships_valid_status",
        "tenant_memberships",
        "status IN ('active', 'suspended', 'revoked')",
        schema="core",
    )

    # --- core.invitations (global, not RLS-scoped) ------------------------
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            sa.ForeignKey("core.tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("invited_email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False, unique=True),
        sa.Column("inviter_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("expires_at > created_at", name="ck_invitations_valid_time_range"),
        sa.CheckConstraint(
            "(accepted_at IS NULL AND accepted_by_user_id IS NULL) "
            "OR (accepted_at IS NOT NULL AND accepted_by_user_id IS NOT NULL)",
            name="ck_invitations_acceptance_pairing",
        ),
        sa.CheckConstraint(
            "(revoked_at IS NULL AND revoked_by_user_id IS NULL) "
            "OR (revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL)",
            name="ck_invitations_revocation_pairing",
        ),
        sa.CheckConstraint(
            "NOT (accepted_at IS NOT NULL AND revoked_at IS NOT NULL)",
            name="ck_invitations_not_accepted_and_revoked",
        ),
        schema="core",
    )
    op.create_index("ix_invitations_tenant_id", "invitations", ["tenant_id"], schema="core")
    op.create_index(
        "ix_invitations_tenant_email", "invitations", ["tenant_id", "invited_email"], schema="core"
    )
    op.create_index(
        "uq_invitations_live_unique",
        "invitations",
        ["tenant_id", "invited_email"],
        unique=True,
        schema="core",
        postgresql_where=sa.text("accepted_at IS NULL AND revoked_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_table("invitations", schema="core")

    op.drop_constraint(
        "ck_tenant_memberships_valid_status", "tenant_memberships", schema="core", type_="check"
    )
    op.drop_column("tenant_memberships", "status", schema="core")
