"""add support access requests and audit linkage columns

Revision ID: 9aecff1d1135
Revises: 5964e254eeb6
Create Date: 2026-09-11 00:00:00.000000

Architecture research: universal multi-tenant tenancy, Phase F ("Audit +
Support Access"). See `core/rbac/models.py::SupportAccessRequest` for the
full model this migration's `core.support_access_requests` table
enforces, `core/rbac/authorization.py::can()` for how it is evaluated
(checked last, after ordinary and delegated allow, never ahead of
explicit deny), and `core/audit_log/models.py::AuditLogEntry` for the
three new linkage columns.

Additive to the existing schema (Phases 3.1-3.4, A-E), nothing removed or
retyped -- one new table, plus three new nullable columns and one new
CHECK on an existing table:

`core.support_access_requests` -- tenant-owned, RLS-protected (identical
single-GUC `app.tenant_id` policy shape `infra.db.rls.tenant_rls_statements()`
applies to every other tenant-owned table, nothing hierarchy-aware, no
`app.authorized_tenant_ids`). One row is the entire request/approval/
denial/revocation lifecycle -- no separate "request" vs. "grant" table,
and no stored status column (the conceptual lifecycle REQUESTED ->
APPROVED -> ACTIVE -> EXPIRED/REVOKED/DENIED is a read-time projection of
this row's timestamps, `core/rbac/support_status.py`). `scope_mode`
reuses the same `'self'`/`'subtree'` value space `core.membership_roles.scope`/
`core.delegation_grants.scope_mode`/`core.deny_grants.scope_mode`/
`core.service_account_roles.scope` already use. `requested_expires_at` is
`NOT NULL` (unlike `core.delegation_grants.expires_at`) -- a support
grant's own security requirement is "have a bounded expiration", not
"optionally have one". Six `CHECK` constraints enforce, at the database
level, the exact pairing/ordering invariants `SupportAccessRequest`'s own
docstring describes (approval/denial/revocation pairing, "not both
approved and denied", "revoke requires prior approval", "no
self-approval") -- an application bug cannot produce a row violating any
of them, even via direct SQL.

`core.audit_log` (`2e7cb8c64903`) gains three new nullable columns --
`acting_as_tenant_id` (FK `core.tenants.id`), `delegation_grant_id` (FK
`core.delegation_grants.id`), `support_access_id` (FK
`core.support_access_requests.id`) -- plus one new CHECK
(`ck_audit_log_single_authorization_linkage`: at most one of
`delegation_grant_id`/`support_access_id` may be set on the same row).
Every existing row has all three new columns `NULL`, trivially satisfying
the new CHECK (`NOT (NULL IS NOT NULL AND NULL IS NOT NULL)` is `NOT
(false AND false)` = true) -- no existing row is affected, and `ActorType`
itself (still exactly `'user'`/`'system'`) is completely untouched.

No RLS change to any other table, no `app.authorized_tenant_ids`, no
`SECURITY DEFINER`, no `BYPASSRLS`, no change to
`validate_application_role()`. `core.support_access_requests` must be
created BEFORE `core.audit_log.support_access_id`'s FK can reference it --
this migration does so in that order.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role. No explicit GRANT
statement is needed for the new table: `e99c76057719`'s `ALTER DEFAULT
PRIVILEGES IN SCHEMA core` rule already grants the runtime role
(`APP_DB_USER`, default `saas_os_app`) SELECT/INSERT/UPDATE/DELETE on any
new table the same bootstrap role creates in `core`; altering
`core.audit_log`'s columns/constraints needs no new GRANT at all (grants
are table-level, not column-level) -- note `core.audit_log` itself
already has UPDATE/DELETE REVOKEd from the runtime role
(`2e7cb8c64903`), unaffected by this migration.

Downgrade reverses every change in the opposite dependency order (drop
the `audit_log` additions first, then the new table -- `audit_log`'s own
`support_access_id` FK must be gone before the table it references can
be dropped).

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "9aecff1d1135"
down_revision: str | Sequence[str] | None = "5964e254eeb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- core.support_access_requests --------------------------------
    op.create_table(
        "support_access_requests",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            sa.ForeignKey("core.tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("requester_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=False),
        sa.Column("scope_mode", sa.String(length=20), nullable=False, server_default="self"),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "requested_starts_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("requested_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column("denied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("denied_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_user_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "scope_mode IN ('self', 'subtree')",
            name="ck_support_access_requests_valid_scope_mode",
        ),
        sa.CheckConstraint(
            "requested_expires_at > requested_starts_at",
            name="ck_support_access_requests_valid_time_range",
        ),
        sa.CheckConstraint(
            "(approved_at IS NULL AND approved_by_user_id IS NULL) "
            "OR (approved_at IS NOT NULL AND approved_by_user_id IS NOT NULL)",
            name="ck_support_access_requests_approval_pairing",
        ),
        sa.CheckConstraint(
            "(denied_at IS NULL AND denied_by_user_id IS NULL) "
            "OR (denied_at IS NOT NULL AND denied_by_user_id IS NOT NULL)",
            name="ck_support_access_requests_denial_pairing",
        ),
        sa.CheckConstraint(
            "(revoked_at IS NULL AND revoked_by_user_id IS NULL) "
            "OR (revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL)",
            name="ck_support_access_requests_revocation_pairing",
        ),
        sa.CheckConstraint(
            "NOT (approved_at IS NOT NULL AND denied_at IS NOT NULL)",
            name="ck_support_access_requests_not_approved_and_denied",
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR approved_at IS NOT NULL",
            name="ck_support_access_requests_revoke_requires_approval",
        ),
        sa.CheckConstraint(
            "approved_by_user_id IS NULL OR approved_by_user_id != requester_user_id",
            name="ck_support_access_requests_no_self_approval",
        ),
        schema="core",
    )
    op.create_index(
        "ix_support_access_requests_tenant_requester",
        "support_access_requests",
        ["tenant_id", "requester_user_id"],
        schema="core",
    )
    op.create_index(
        "uq_support_access_requests_live_unique",
        "support_access_requests",
        ["tenant_id", "requester_user_id", "scope_mode"],
        unique=True,
        schema="core",
        postgresql_where=sa.text("denied_at IS NULL AND revoked_at IS NULL"),
    )
    for statement in tenant_rls_statements("support_access_requests", schema="core"):
        op.execute(statement)

    # --- core.audit_log: privileged cross-tenant linkage ----------------
    op.add_column(
        "audit_log",
        sa.Column(
            "acting_as_tenant_id", sa.Uuid(), sa.ForeignKey("core.tenants.id"), nullable=True
        ),
        schema="core",
    )
    op.add_column(
        "audit_log",
        sa.Column(
            "delegation_grant_id",
            sa.Uuid(),
            sa.ForeignKey("core.delegation_grants.id"),
            nullable=True,
        ),
        schema="core",
    )
    op.add_column(
        "audit_log",
        sa.Column(
            "support_access_id",
            sa.Uuid(),
            sa.ForeignKey("core.support_access_requests.id"),
            nullable=True,
        ),
        schema="core",
    )
    op.create_check_constraint(
        "ck_audit_log_single_authorization_linkage",
        "audit_log",
        "NOT (delegation_grant_id IS NOT NULL AND support_access_id IS NOT NULL)",
        schema="core",
    )


def downgrade() -> None:
    # --- core.audit_log ---------------------------------------------------
    op.drop_constraint(
        "ck_audit_log_single_authorization_linkage", "audit_log", schema="core", type_="check"
    )
    op.drop_column("audit_log", "support_access_id", schema="core")
    op.drop_column("audit_log", "delegation_grant_id", schema="core")
    op.drop_column("audit_log", "acting_as_tenant_id", schema="core")

    # --- core.support_access_requests -------------------------------------
    op.drop_table("support_access_requests", schema="core")
