"""add scope to core.membership_roles (self/subtree)

Revision ID: a17e5f3c9d84
Revises: 6b4f2d8a91c3
Create Date: 2026-09-10 00:00:00.000000

Architecture research: universal multi-tenant tenancy, Phase B ("RBAC +
role scope: self, subtree"). See `core/rbac/scope.py` and
`core/rbac/models.py::MembershipRole` for the full semantics this
migration's schema enforces, and `core/rbac/authorization.py::can()` for
how it is evaluated.

One additive change to the existing `core/rbac` schema (Phase 3.3),
nothing removed or retyped: `core.membership_roles` gains a `scope`
column, `NOT NULL` with `server_default='self'` -- every row that already
existed before this migration, and any row an older/uninstrumented
codepath might still insert without knowing the column exists, becomes
`'self'`: the exact, only behavior a `MembershipRole` assignment could
ever have meant before this phase existed (a role reaching only its own
membership's tenant, never any descendant). This is the "safe default
corresponding to the current authorization behavior" the architecture
research requires -- existing assignments are never silently widened to
`'subtree'`.

A `CHECK` constraint restricts the column to exactly `'self'`/`'subtree'`
at the database level, mirroring `core.tenants.status`'s and
`core.tenant_ancestry.depth`'s own `CHECK`-constrained-string/int
conventions (`e99c76057719`, `6b4f2d8a91c3`) -- an invalid scope is
rejected by PostgreSQL itself, not merely by `RoleScope`'s Python type
system.

No RLS change: `core.membership_roles` was already RLS-protected
(`81ac56902107`); adding a column to an existing RLS-protected table does
not touch its policy, which still reads only `tenant_id`. No
`app.authorized_tenant_ids`, no `SECURITY DEFINER`, no `BYPASSRLS`, no
change to `validate_application_role()`.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role. No explicit GRANT
statement is needed: `GRANT`s are table-level (not column-level), and
`core.membership_roles` already has one from `81ac56902107`'s own
`ALTER DEFAULT PRIVILEGES` inheritance chain (`e99c76057719`).

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a17e5f3c9d84"
down_revision: str | Sequence[str] | None = "6b4f2d8a91c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "membership_roles",
        sa.Column("scope", sa.String(length=20), nullable=False, server_default="self"),
        schema="core",
    )
    op.create_check_constraint(
        "ck_membership_roles_valid_scope",
        "membership_roles",
        "scope IN ('self', 'subtree')",
        schema="core",
    )


def downgrade() -> None:
    op.drop_constraint(
        "ck_membership_roles_valid_scope", "membership_roles", schema="core", type_="check"
    )
    op.drop_column("membership_roles", "scope", schema="core")
