"""add audit_log service account actor attribution

Revision ID: a8ad8e61deb2
Revises: d9da5514672b
Create Date: 2026-09-13 00:00:00.000000

Phase J-RBAC-02 -- "Service Account Audit Attribution": remediates the
forensic gap where a service-account-owned API key's own audit events
(`core/api_keys/service.py::validate_api_key()`/`revoke_api_key()`/
`rotate_api_key()`) had no way to name the service account as the actor
-- they collapsed to `actor_type='system'` with no id at all, discarding
`ApiKey.service_account_id` entirely. See `core/audit_log/models.py
::ActorType`/`AuditLogEntry` for the full model this migration's schema
change enforces.

Additive to the existing schema, nothing removed or retyped -- one new
nullable column, one new composite foreign key, and the existing actor
CHECK constraints widened (dropped and recreated, since PostgreSQL has no
`ALTER CONSTRAINT ... ADD VALUE` for a plain CHECK) to admit the new
value:

`core.audit_log` gains `actor_service_account_id` (nullable UUID,
composite FK `(tenant_id, actor_service_account_id) ->
core.service_accounts(tenant_id, id)` -- the identical composite-FK
discipline `3a2522ccb9ea`'s `core.api_keys` already established for
`(tenant_id, service_account_id)`, applied here identically: a service
account named as an audit actor can only ever be one that genuinely
belongs to that same row's own `tenant_id`, enforced by Postgres itself,
never merely by application code remembering to check). `ck_audit_log_actor_type`
now reads `actor_type IN ('user', 'system', 'service_account')` (was
`IN ('user', 'system')`). `ck_audit_log_actor_type_user_id_pairing` now
additionally requires a `'service_account'` row to carry
`actor_service_account_id` (and no `actor_user_id`), symmetric with the
existing `'user'`/`'system'` cases.

Every existing row has `actor_service_account_id NULL` and `actor_type`
already in `{'user', 'system'}` -- both widened CHECKs are satisfied
trivially by every such row (the new `OR` branch simply never applies to
it), so no existing row is rewritten, no existing row is affected, and no
data migration of any kind runs here. `core.api_keys`/`core.service_accounts`
themselves are entirely unchanged -- this migration touches only
`core.audit_log`.

No RLS change (this migration adds a column and constraints to an
already-RLS-protected table, `2e7cb8c64903`; RLS itself is untouched), no
`app.authorized_tenant_ids`, no `SECURITY DEFINER`, no `BYPASSRLS`, no
change to `validate_application_role()`, no change to
`core.audit_log`'s own REVOKEd UPDATE/DELETE privileges
(`2e7cb8c64903`) -- altering columns/constraints needs no new GRANT
(grants are table-level, not column-level).

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`,
`MIGRATIONS_DATABASE_URL`) -- never the restricted application runtime
role.

Downgrade reverses every change in the opposite order: restore the two
original two-value CHECK constraints, drop the new composite FK, drop the
new column. A downgrade run against a database holding a real
`actor_type='service_account'` row would violate the restored
`ck_audit_log_actor_type` CHECK and fail loudly (the correct, fail-closed
behavior for a destructive downgrade that cannot represent that row
anymore) -- exactly the same "downgrade requires no data using the
removed shape" precondition every other additive-then-narrowing migration
in this history already carries.

Preserves the two independent Alembic histories (docs/architecture/
SAAS-OS-DISTRIBUTION-ARCHITECTURE.md ADR-0016): this migration lives
entirely in SaaS OS's own `infra/db/migrations/versions/` history; no
consumer-project migration is touched or needs to be.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's
docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8ad8e61deb2"
down_revision: str | Sequence[str] | None = "d9da5514672b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_ACTOR_TYPE_CHECK = "actor_type IN ('user', 'system')"
_NEW_ACTOR_TYPE_CHECK = "actor_type IN ('user', 'system', 'service_account')"

_OLD_PAIRING_CHECK = (
    "(actor_type = 'user' AND actor_user_id IS NOT NULL) "
    "OR (actor_type = 'system' AND actor_user_id IS NULL)"
)
_NEW_PAIRING_CHECK = (
    "(actor_type = 'user' AND actor_user_id IS NOT NULL AND actor_service_account_id IS NULL) "
    "OR (actor_type = 'system' AND actor_user_id IS NULL AND actor_service_account_id IS NULL) "
    "OR (actor_type = 'service_account' AND actor_user_id IS NULL "
    "AND actor_service_account_id IS NOT NULL)"
)


def upgrade() -> None:
    op.add_column(
        "audit_log",
        sa.Column("actor_service_account_id", sa.Uuid(), nullable=True),
        schema="core",
    )
    op.create_foreign_key(
        "fk_audit_log_tenant_service_account",
        "audit_log",
        "service_accounts",
        ["tenant_id", "actor_service_account_id"],
        ["tenant_id", "id"],
        source_schema="core",
        referent_schema="core",
    )

    op.drop_constraint("ck_audit_log_actor_type_user_id_pairing", "audit_log", schema="core")
    op.drop_constraint("ck_audit_log_actor_type", "audit_log", schema="core")
    op.create_check_constraint(
        "ck_audit_log_actor_type", "audit_log", _NEW_ACTOR_TYPE_CHECK, schema="core"
    )
    op.create_check_constraint(
        "ck_audit_log_actor_type_user_id_pairing",
        "audit_log",
        _NEW_PAIRING_CHECK,
        schema="core",
    )


def downgrade() -> None:
    op.drop_constraint("ck_audit_log_actor_type_user_id_pairing", "audit_log", schema="core")
    op.drop_constraint("ck_audit_log_actor_type", "audit_log", schema="core")
    op.create_check_constraint(
        "ck_audit_log_actor_type", "audit_log", _OLD_ACTOR_TYPE_CHECK, schema="core"
    )
    op.create_check_constraint(
        "ck_audit_log_actor_type_user_id_pairing",
        "audit_log",
        _OLD_PAIRING_CHECK,
        schema="core",
    )

    op.drop_constraint(
        "fk_audit_log_tenant_service_account", "audit_log", schema="core", type_="foreignkey"
    )
    op.drop_column("audit_log", "actor_service_account_id", schema="core")
