"""create core.delegation_grants table

Revision ID: c92f4b81e6a7
Revises: a17e5f3c9d84
Create Date: 2026-09-11 00:00:00.000000

Architecture research: universal multi-tenant tenancy, Phase C
("Delegation" -- an explicit, bilateral, scoped, revocable primitive,
intentionally separate from hierarchy). See `core/rbac/models.py`'s
`DelegationGrant` docstring for the full model this migration's schema
enforces, and `core/rbac/authorization.py` for how it is evaluated.

One new table, additive to the existing `core/rbac` schema (Phase 3.3),
nothing removed or retyped:

`core.delegation_grants` -- tenant-owned, RLS-protected exactly like
`core.roles`/`core.membership_roles` (`tenant_id` here names the tenant
the grant's authority *concerns* -- the "scope tenant", the same
convention every other `core/rbac` table already uses for "the tenant
this row's authority belongs to").

Principals are `(principal_type, principal_id)` pairs, not a bare
`user_id` (architecture research: "Do NOT create a physical unified
Principal table... use... principal_type / principal_id"). This phase
supports only `'user'`/`'system'` values (mirroring
`core.audit_log.actor_type`'s own two-value discipline exactly) and only
ever *constructs* `'user'` rows -- `'system'` exists in the schema for
forward compatibility, not because any code path in this phase produces
one. Both principal columns are `CHECK`-paired with their `_id` column
(non-null iff `'user'`, null iff `'system'`) the same way
`core.audit_log.actor_type`/`actor_user_id` already are.

`scope_mode` reuses `core.membership_roles.scope`'s own value space
(`'self'`/`'subtree'`, `core/rbac/scope.py::RoleScope`) rather than a
new, incompatible enum. `permission_id` is a **global** `core.permissions`
reference (plain FK, no composite-FK tenant pairing -- `Permission` is
not tenant-owned) -- a `DelegationGrant` never references a tenant-local
`Role`, since a `Role` cannot express delegating a capability into an
unrelated tenant the way a global `Permission` reference does.

`tenant_id`'s foreign key uses `ON DELETE CASCADE` -- unlike
`core.tenants.parent_id`'s plain (blocking) FK, a delegation grant has no
meaning once its own scope tenant no longer exists, the same reasoning
`core.tenant_ancestry` already applies (`6b4f2d8a91c3`). `delegator_
principal_id`/`delegate_principal_id`/`permission_id` all use plain,
non-cascading FKs, matching every other reference to `core.users`/
`core.permissions` in this schema (no user- or permission-deletion path
exists in this codebase to cascade from).

A `CHECK` enforces `expires_at IS NULL OR expires_at > starts_at`
("enforce valid temporal relationships"). A partial unique index
(`revoked_at IS NULL` only) blocks an accidental duplicate *active* grant
(same tenant/delegate/scope/permission) without blocking a legitimate
second grant that differs in scope, permission, or validity window, and
without blocking re-granting after a prior grant was revoked or expired.

No RLS change to any other table, no `app.authorized_tenant_ids`, no
`SECURITY DEFINER`, no `BYPASSRLS`, no change to
`validate_application_role()` -- `core.delegation_grants` gets exactly
the same single-GUC (`app.tenant_id`) policy shape
`infra.db.rls.tenant_rls_statements()` applies to every other
tenant-owned table, nothing hierarchy-aware.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role. No explicit GRANT
statement is needed: `e99c76057719`'s `ALTER DEFAULT PRIVILEGES IN SCHEMA
core` rule already grants the runtime role (`APP_DB_USER`, default
`saas_os_app`) SELECT/INSERT/UPDATE/DELETE on any new table the same
bootstrap role creates in `core`.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "c92f4b81e6a7"
down_revision: str | Sequence[str] | None = "a17e5f3c9d84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "delegation_grants",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            sa.ForeignKey("core.tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "delegator_principal_type", sa.String(length=20), nullable=False, server_default="user"
        ),
        sa.Column(
            "delegator_principal_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True
        ),
        sa.Column(
            "delegate_principal_type", sa.String(length=20), nullable=False, server_default="user"
        ),
        sa.Column(
            "delegate_principal_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True
        ),
        sa.Column("scope_mode", sa.String(length=20), nullable=False, server_default="self"),
        sa.Column("permission_id", sa.Uuid(), sa.ForeignKey("core.permissions.id"), nullable=False),
        sa.Column(
            "starts_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("allow_redelegate", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "delegator_principal_type IN ('user', 'system')",
            name="ck_delegation_grants_delegator_principal_type",
        ),
        sa.CheckConstraint(
            "(delegator_principal_type = 'user' AND delegator_principal_id IS NOT NULL) "
            "OR (delegator_principal_type = 'system' AND delegator_principal_id IS NULL)",
            name="ck_delegation_grants_delegator_pairing",
        ),
        sa.CheckConstraint(
            "delegate_principal_type IN ('user', 'system')",
            name="ck_delegation_grants_delegate_principal_type",
        ),
        sa.CheckConstraint(
            "(delegate_principal_type = 'user' AND delegate_principal_id IS NOT NULL) "
            "OR (delegate_principal_type = 'system' AND delegate_principal_id IS NULL)",
            name="ck_delegation_grants_delegate_pairing",
        ),
        sa.CheckConstraint(
            "scope_mode IN ('self', 'subtree')", name="ck_delegation_grants_valid_scope_mode"
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > starts_at",
            name="ck_delegation_grants_valid_time_range",
        ),
        schema="core",
    )

    op.create_index(
        "ix_delegation_grants_tenant_delegate",
        "delegation_grants",
        ["tenant_id", "delegate_principal_type", "delegate_principal_id"],
        schema="core",
    )
    # Partial unique index, active grants only -- see module docstring.
    op.create_index(
        "uq_delegation_grants_active_unique",
        "delegation_grants",
        [
            "tenant_id",
            "delegate_principal_type",
            "delegate_principal_id",
            "scope_mode",
            "permission_id",
        ],
        unique=True,
        schema="core",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )

    for statement in tenant_rls_statements("delegation_grants", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("delegation_grants", schema="core")
