"""create core.deny_grants table

Revision ID: ccdbecd208f7
Revises: c92f4b81e6a7
Create Date: 2026-09-11 00:00:00.000000

Architecture research: universal multi-tenant tenancy, Phase D
("Explicit Deny" -- "DENY overrides ALLOW"). See `core/rbac/models.py`'s
`DenyGrant` docstring for the full model this migration's schema
enforces, and `core/rbac/authorization.py` for how it is evaluated
(checked first, before any allow path, in `can()`).

One new table, additive to the existing `core/rbac` schema (Phases 3.3,
B, C), nothing removed or retyped:

`core.deny_grants` -- tenant-owned, RLS-protected exactly like
`core.delegation_grants` (`tenant_id` here names the tenant the deny's
scope *concerns*, the same convention every other `core/rbac` table
already uses).

Principals are `(principal_type, principal_id)` pairs, mirroring
`core.delegation_grants`'s own delegate columns exactly -- this phase
supports only `'user'`/`'system'` values and only ever *constructs*
`'user'` rows. `principal_type`/`principal_id` are `CHECK`-paired
identically to `core.delegation_grants.delegate_principal_type`/
`delegate_principal_id`.

`scope_mode` reuses `core.membership_roles.scope`'s/
`core.delegation_grants.scope_mode`'s own value space (`'self'`/
`'subtree'`, `core/rbac/scope.py::RoleScope`). `permission_id` is a
**global** `core.permissions` reference (plain FK, no composite-FK
tenant pairing), identical reasoning to `core.delegation_grants.permission_id`.

Unlike `core.delegation_grants`, this table has **no** `starts_at`/
`expires_at` columns -- a deny is a restrictive control, not a grant, so
the safe default on "forgotten lifecycle management" is the opposite of
a delegation's: a deny that is never revoked should keep blocking
forever, not silently lapse (`core/rbac/models.py::DenyGrant`'s own
docstring). Only `revoked_at` models its lifecycle.

`tenant_id`'s foreign key uses `ON DELETE CASCADE`, identical reasoning
to `core.delegation_grants.tenant_id` (`c92f4b81e6a7`) -- a deny grant
has no meaning once its own scope tenant no longer exists.
`principal_id`/`permission_id` use plain, non-cascading FKs, matching
every other reference to `core.users`/`core.permissions` in this schema.

No `CHECK` on time range (there is no time range). A partial unique index
(`revoked_at IS NULL` only) blocks an accidental duplicate *active* deny
(same tenant/principal/scope/permission) without blocking a legitimate
second deny that differs in scope or permission, and without blocking
re-denying after a prior deny was revoked -- identical reasoning to
`uq_delegation_grants_active_unique`.

No RLS change to any other table, no `app.authorized_tenant_ids`, no
`SECURITY DEFINER`, no `BYPASSRLS`, no change to
`validate_application_role()` -- `core.deny_grants` gets exactly the same
single-GUC (`app.tenant_id`) policy shape
`infra.db.rls.tenant_rls_statements()` applies to every other
tenant-owned table, nothing hierarchy-aware.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role. No explicit GRANT
statement is needed: `e99c76057719`'s `ALTER DEFAULT PRIVILEGES IN SCHEMA
core` rule already grants the runtime role (`APP_DB_USER`, default
`saas_os_app`) SELECT/INSERT/UPDATE/DELETE on any new table the same
bootstrap role creates in `core`.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from infra.db.rls import tenant_rls_statements

# revision identifiers, used by Alembic.
revision: str = "ccdbecd208f7"
down_revision: str | Sequence[str] | None = "c92f4b81e6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "deny_grants",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            sa.ForeignKey("core.tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("principal_type", sa.String(length=20), nullable=False, server_default="user"),
        sa.Column("principal_id", sa.Uuid(), sa.ForeignKey("core.users.id"), nullable=True),
        sa.Column("scope_mode", sa.String(length=20), nullable=False, server_default="self"),
        sa.Column("permission_id", sa.Uuid(), sa.ForeignKey("core.permissions.id"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "principal_type IN ('user', 'system')",
            name="ck_deny_grants_principal_type",
        ),
        sa.CheckConstraint(
            "(principal_type = 'user' AND principal_id IS NOT NULL) "
            "OR (principal_type = 'system' AND principal_id IS NULL)",
            name="ck_deny_grants_principal_pairing",
        ),
        sa.CheckConstraint(
            "scope_mode IN ('self', 'subtree')", name="ck_deny_grants_valid_scope_mode"
        ),
        schema="core",
    )

    op.create_index(
        "ix_deny_grants_tenant_principal",
        "deny_grants",
        ["tenant_id", "principal_type", "principal_id"],
        schema="core",
    )
    # Partial unique index, active denies only -- see module docstring.
    op.create_index(
        "uq_deny_grants_active_unique",
        "deny_grants",
        ["tenant_id", "principal_type", "principal_id", "scope_mode", "permission_id"],
        unique=True,
        schema="core",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )

    for statement in tenant_rls_statements("deny_grants", schema="core"):
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("deny_grants", schema="core")
