"""add tenant billing inheritance flag

Revision ID: d9da5514672b
Revises: 87efe7908288
Create Date: 2026-09-12 00:00:00.000000

Architecture research: universal multi-tenant tenancy, Phase H
("Hierarchy-Aware Billing & Usage"). See `core/tenancy/models.py::Tenant
.inherits_billing` for the full field semantics, and
`core/billing/service.py::resolve_billing_owner()` for how it is
evaluated (never authorization -- entitlement resolution only).

One additive change to the existing schema (Phases 3.1-3.4, A-G): `core.tenants`
gains an `inherits_billing` column, `NOT NULL` with `server_default=false`
-- every tenant that already existed before this migration becomes
`False`: the exact, only behavior a `Tenant` row could ever have meant
before this phase existed (it resolves its own billing, exactly the flat,
single-tenant behavior every pre-Phase-H caller of
`core.billing.service.get_entitlements()` already gets). This is the same
"safe default corresponding to the current authorization/entitlement
behavior" discipline `a17e5f3c9d84` (membership-role scope) and
`87efe7908288` (membership status) already established for this exact
kind of additive, backwards-compatible column -- no existing tenant's
billing resolution changes as a result of this migration.

No new table, no RLS change (`core.tenants` is not, and has never been,
RLS-scoped -- `core/tenancy/models.py`'s own docstring), no
`app.authorized_tenant_ids`, no `SECURITY DEFINER`, no `BYPASSRLS`, no
change to `validate_application_role()`. `core.tenant_ancestry` is
completely untouched by this migration -- hierarchy structure and billing
configuration are stored in two independent columns/tables, exactly as
this phase's own design requires ("hierarchy MUST NOT implicitly grant
authorization" -- and, symmetrically here, structure must not imply
billing configuration either; `inherits_billing` is a separate, explicit
flag, never inferred from `parent_id`).

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`, `MIGRATIONS_DATABASE_URL`)
-- never the restricted application runtime role. No explicit GRANT
statement is needed: `GRANT`s are table-level (not column-level), and
`core.tenants` already has one from `e99c76057719`'s own `ALTER DEFAULT
PRIVILEGES` inheritance chain.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9da5514672b"
down_revision: str | Sequence[str] | None = "87efe7908288"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "tenants",
        sa.Column("inherits_billing", sa.Boolean(), nullable=False, server_default=sa.false()),
        schema="core",
    )


def downgrade() -> None:
    op.drop_column("tenants", "inherits_billing", schema="core")
