"""create core tenants table

Revision ID: e99c76057719
Revises:
Create Date: 2026-09-06 23:19:14.495271

docs/IMPLEMENTATION-ROADMAP.md Phase 3.1; docs/DATA-ARCHITECTURE.md
section 1: `core.tenants`, owned exclusively by `core/tenancy`.

`core.tenants` is deliberately not Row-Level-Security-scoped -- see
`core/tenancy/models.py`'s docstring for why (a session must be able to
resolve which tenant it belongs to before any tenant context exists).
Future tenant-*owned* tables apply `infra.db.rls.tenant_rls_statements()`
in their own migrations; this table does not.

Runs via the privileged bootstrap/migration role
(`infra.db.config.get_migrations_database_config()`,
`MIGRATIONS_DATABASE_URL`) -- never the restricted application runtime
role. Grants the runtime role (`APP_DB_USER`, default `saas_os_app` for
local dev) exactly the DML privileges normal application operation needs
on this table, plus a schema-level `ALTER DEFAULT PRIVILEGES` rule so any
*future* table this same migration role creates in `core` automatically
grants the same DML to the runtime role -- one place to get this right,
not something every future migration must remember (docs/IMPLEMENTATION-ROADMAP.md
Phase 3.1 security correction: the runtime role must never be a
superuser/BYPASSRLS/table-owner escape hatch around Row-Level Security).
The role itself is created by `infra/db/init/01-create-app-role.sh`
(Docker's own bootstrap mechanism), not by this migration.

Hand-written, not autogenerated -- `infra/db/migrations/env.py`'s
`target_metadata` remains `None` deliberately (see that file's docstring):
wiring autogenerate to diff against Core's tables is a separate concern
this phase does not need to solve, and a half-wired autogenerate setup
that saw `infra.db.orm.Base.metadata` but not `core.tenancy.models.Tenant`
(never imported by `infra/db`, which must not depend on `core`) would be
actively misleading -- it would think this table shouldn't exist.
"""

import os
import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e99c76057719"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DEFAULT_APP_ROLE = "saas_os_app"


def _app_role() -> str:
    # A role NAME is not a secret (docs/ADR/0012-secrets-management.md is
    # about credential *values*) -- read directly like other non-secret
    # config (ENVIRONMENT, JOBS_MAX_TRIES, ...) rather than through
    # infra.secrets. Restricted to a safe identifier shape since it is
    # interpolated into DDL text (op.execute has no identifier-binding
    # mechanism) -- this is trusted deployment configuration, not user
    # input, but the check costs nothing and rules out accidents.
    role = os.environ.get("APP_DB_USER", _DEFAULT_APP_ROLE)
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", role):
        raise ValueError(f"APP_DB_USER must be a plain SQL identifier, got: {role!r}")
    return role


def upgrade() -> None:
    app_role = _app_role()

    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        schema="core",
    )

    op.execute(f'GRANT USAGE ON SCHEMA core TO "{app_role}"')
    op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON core.tenants TO "{app_role}"')
    # No `FOR ROLE` clause: defaults to "objects the current session's role
    # creates" -- i.e. this migration's own (bootstrap) role, whatever its
    # name, without needing to know or guess it.
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA core "
        f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "{app_role}"'
    )


def downgrade() -> None:
    app_role = _app_role()

    # Default-privilege rules are not tied to the schema's lifecycle and
    # would otherwise survive DROP SCHEMA, silently reapplying if `core`
    # is ever recreated.
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA core "
        f'REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM "{app_role}"'
    )
    op.drop_table("tenants", schema="core")
    # No CASCADE: if a later migration has added another table to the
    # `core` schema, this deliberately fails rather than silently
    # dropping data that does not belong to this migration.
    op.execute("DROP SCHEMA IF EXISTS core")
